### ISSUE TITLE
[Feature Request] Add support for Lichess

### ISSUE THREAD

**Issue by i-am-zach** [shuhaoli/hikaru-gotham-move#12]
I'm not sure if this is already a feature. I looked through the `js/chessMoveReminder.js` file and it looks like you only scraped for the chess.com urls so I'm guessing there is no Lichess support. If this is the case, I wouldn't mind forking the project adding the support myself. We'd probably have to email Lichess support like you did for chess.com beforehand.

By the way, loved the video! Keep up the great content.

**Comment by shuhaoli** [comment]
Hi Zach, Lichess support was actually added in recently! https://github.com/shuhaoli/hikaru-gotham-move/issues/2
