### ISSUE TITLE
Extension randomly not working on firefox (fix included)

### ISSUE THREAD

**Issue by kbios** [shuhaoli/hikaru-gotham-move#16]
Hi, I found out that quite often this extension is not working for me (Firefox 81 on linux, chess.com). It seems that the onload event is not being consistently fired. I fixed it by simply making the pageReloadObserver top-level, like so:

```
setTimeout(chessMoveReminder, 1000);
let bodyList = document.querySelector('body');
let pageReloadObserver = new MutationObserver(function (mutations) {
    mutations.forEach(function (mutation) {
        if (oldHref !== document.location.href) {
            clearTimeout(timer);
            oldHref = document.location.href;
            setTimeout(chessMoveReminder, 1000);
        }
    });
});
let config = {
    childList: true,
    subtree: true,
};

pageReloadObserver.observe(bodyList, config);
```

This also avoids having to save and manually fire the original window onload()

**Comment by shuhaoli** [comment]
Thanks for the fix! https://github.com/shuhaoli/hikaru-gotham-move/commit/04dea1307c31efed2d94d8df7cf87d43e5499228
