### ISSUE TITLE
Support for Lichess

### ISSUE THREAD

**Issue by shuhaoli** [shuhaoli/hikaru-gotham-move#2]
This is a highly requested feature as a number of players play on Lichess.

**Comment by hlee131** [comment]
Can I take this issue?

**Comment by shuhaoli** [comment]
Feel free to take on this issue!

**Comment by hlee131** [comment]
Are there any known issues with installation? I tried installing to understand the code but it doesn't seem to be working.

**Comment by shuhaoli** [comment]
I don't believe there are any issues - I asked a few people who seemed to have installed it perfectly fine. What errors are you getting?

**Comment by hlee131** [comment]
No specific error, but just that it doesn't do anything after installation.
